apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetmysql
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: dotnetmysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dotnetmysql
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: "dotnet-sandbox"
        tags.datadoghq.com/service: "dotnetmysql"
        tags.datadoghq.com/version: "latest"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: latest
    spec:
      containers:
      - name: dotnetmysql
        image: daniellee19900407/dotnetmysql:latest
        ports:
        - containerPort: 8080
        env:
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_RUNTIME_METRICS_ENABLED
          value: "true"
        - name: DD_APPSEC_ENABLED
          value: "true"
---

apiVersion: v1
kind: Service
metadata:
  name: dotnetmysql
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: dotnetmysql